apiVersion: v1
kind: ConfigMap
metadata:
  name: epg-v3-rollback-{{ .Values.partner }}-conf
  namespace: default
data:
  appsettings.json: |
    {
      "PartnerId": {{ .Values.partner }},
      "BatchSize": {{ .Values.batch_size }},
      "OriginalEpgVersion": {{ .Values.original_epg_version }},
      "PreserveDataFromV3": {{ .Values.preserve_data_from_v3 }},
      "RollbackFromBackup": {{ .Values.rollback_from_backup_epg_v2 }}
    }
