apiVersion: v1
kind: ConfigMap
metadata:
  name: epg-v3-migrator-{{ .Values.partner }}-conf
  namespace: default
data:
  appsettings.json: |
    {
      "PartnerId": {{ .Values.partner }},
      "BatchSize": {{ .Values.batch_size }},
      "OriginalEpgVersion": 1
    }
