version: '3'

services:
  elastic02:
    image: elasticsearch:2.3.3
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    command:
      - sh
      - -c
      - "plugin list | grep -q delete-by-query || plugin install delete-by-query;
      -  plugin list | grep -q analysis-icu || plugin install analysis-icu; 
         /docker-entrypoint.sh elasticsearch"
    networks:
      - testbed
  elastic07:
    image: elasticsearch:7.13.4
    environment:
      - discovery.type=single-node
      - node.max_local_storage_nodes=1
    command: 
      - sh
      - -c
      - "bin/elasticsearch-plugin install analysis-icu; 
         /usr/local/bin/docker-entrypoint.sh elasticsearch"
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - testbed

volumes:
  data01:
    driver: local
  data02:
    driver: local
networks:
  testbed:
    driver: bridge