account: "870777418594"
region: us-west-2
cluster_name: ohs1
destination_cluster: https://D3A4D8DAAD18B715E08D0CA2846D52AA.gr7.us-east-2.eks.amazonaws.com
branch: dev

# TCM Config for all components
tcm_from_local: "false"
tcm_url: http://ktcm
tcm_app: OTT_API_VEON
tcm_section: main
tcm_host: MS #PROD_v5_2_2 