account: "681016013154"
region: us-west-2
cluster_name: orp2
destination_cluster: https://CFABC83E9B185339279361BE8E0DFC87.gr7.us-west-2.eks.amazonaws.com
branch: master

# TCM Config for all components
tcm_from_local: "false"
tcm_url: http://ktcm
tcm_app: OTT_API_Modeled_CB6_Linux
tcm_section: main
tcm_host: MS