account: "580180864418"
region: eu-west-3
cluster_name: prd1
destination_cluster: https://711F285D89911CCEADB158F3AC97A87C.yl4.eu-west-3.eks.amazonaws.com
branch: master

# TCM Config for all components
tcm_from_local: "false"
tcm_url: http://ktcm
tcm_app: OTT_API_SV
tcm_section: main
tcm_host: MS
