account: "122637030685"
region: eu-central-1
cluster_name: frt1
destination_cluster: https://98166A766A7108535A48C3AD327E9F60.gr7.eu-central-1.eks.amazonaws.com
branch: dev

# TCM Config for all components
tcm_from_local: "false"
tcm_url: http://ktcm
tcm_app: OTT_API_Modeled_Linux
tcm_app_standby: Handlers_Migration
tcm_section: main
tcm_host: MS