account: "084408580931"
region: eu-west-1
cluster_name: ind1
destination_cluster: https://FAF64B23E05C60E827FDABA6CB7BF476.yl4.eu-west-1.eks.amazonaws.com
branch: dev

# TCM Config for all components
tcm_from_local: "false"
tcm_url: http://ktcm
tcm_app: OTT_API_K8S
tcm_section: PROD_v5_2_2
tcm_host: main