account: "122637030685"
region: ap-southeast-1
cluster_name: sgt2
destination_cluster: https://AF5CD18FEBF6FC8B296DE54FA473457D.yl4.ap-southeast-1.eks.amazonaws.com
branch: dev

# TCM Config for all components
tcm_from_local: "false"
tcm_url: http://ktcm
tcm_app: OTT_API_SV_Linux
tcm_section: main
tcm_host: PROD_v5_3_5