
{{- $chartName := .Chart.Name -}}
{{- $chartVersion := .Chart.Version -}}
{{- $chartAppVersion := .Chart.AppVersion -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $envTag := .Values.env.tag -}}
{{- $envRepository := .Values.env.repository -}}
{{- $firstHandler := (first .Values.handlers).name -}}

{{- range .Values.handlers }}
{{ if not (eq $firstHandler .name) }}
---
{{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ .name }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .name }}
      app.kubernetes.io/instance: {{ $releaseName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/instance: {{ $releaseName }}
        kaltura/tcm-app: REMOTE_TASKS_v{{ $chartVersion | replace "." "_" }}
    spec:
      volumes:
        - name: required-fields
          configMap:
            name: {{ $chartName }}-config-tcm-required-fields
      initContainers:
        - name: "{{$releaseName}}-validate-tcm"
          image: "{{ $envRepository }}/{{ $envTag }}-validate-tcm:latest"
          volumeMounts:
            - name: required-fields
              mountPath: /etc/kaltura/tcm
          env:
            - name: TCM_APP
              value: REMOTE_TASKS_v{{ $chartVersion | replace "." "_" }}
            - name: TCM_SECTION
              value: {{ $envTag }}
            - name: TCM_URL
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.url
            - name: TCM_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appId
            - name: TCM_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appSecret
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
      containers:
        - name: {{ .name }}
          image: "{{ $envRepository }}/{{ $envTag }}-{{ $chartName }}:{{ $chartAppVersion }}"
          imagePullPolicy: Always
          env:
            - name: RUN_TASK
              value: {{ .task }}
            - name: TCM_SECTION
              value: {{ $envTag }}
            - name: TCM_URL
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.url
            - name: TCM_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appId
            - name: TCM_APP_SECRET
              valueFrom:
                configMapKeyRef:
                  name: kaltura-environment
                  key: tcm.appSecret
      strategy:
        type: RollingUpdate
        maxUnavailable: 1
      nodeSelector:
        kaltura.role: core
{{- end }}