LayeredCache: &LayeredCache
  Version: 3
  DefaultSettings:
    - "$type": CachingProvider.LayeredCache.InMemoryLayeredCacheConfig, CachingProvider
      Type: InMemoryCache
      TTL: 3600
    - "$type": CachingProvider.LayeredCache.RedisLayeredCacheConfig, CachingProvider
      Type: Redis
      TTL: 86400
  OnInvalidationKeyConsumeCacheSettings:
    "$type": CachingProvider.LayeredCache.RedisLayeredCacheConfig, CachingProvider
    Type: Redis
    TTL: 86400
  GroupCacheSettings:
    - "$type": CachingProvider.LayeredCache.InMemoryLayeredCacheConfig, CachingProvider
      Type: InMemoryCache
      TTL: 60
    - "$type": CachingProvider.LayeredCache.RedisLayeredCacheConfig, CachingProvider
      Type: Redis
      TTL: 0
      Bucket: Default
  BucketSettings:
    - Bucket: Default
      CacheType: Redis
    - Bucket: Cache
      CacheType: Redis
  InvalidationKeySettings:
    - "$type": CachingProvider.LayeredCache.RedisLayeredCacheConfig, CachingProvider
      Type: Redis
      TTL: 30
      Bucket: Cache

kafka_client_configuration:
  bootstrapServers: localhost:9092
  socketTimeoutMs: 5000

redis_client_configuration:
  cache_database: 0
  cache_address: redis